package com.tryking.trykingcitychoose;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SsoMemberAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.ADDRESS_ID
     */
    private BigDecimal addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.MEMBER_ID
     */
    private BigDecimal memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.RECEIVER
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.PROVINCE
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.CITY
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.AREA
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.ADDRESS_NAME
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.ZIP
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.MOBILE
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.TEL
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.IS_DEFAULT
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.IS_DELETE
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.CREATE_DATE
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.MODIFY_DATE
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.FULL_ADDRESS
     */
    private String fullAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SSO_MEMBER_ADDRESS.ADDRESS_TYPE
     */
    private String addressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SSO_MEMBER_ADDRESS
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_ID
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.ADDRESS_ID
     */
    public BigDecimal getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_ID
     *
     * @param addressId the value for T_SSO_MEMBER_ADDRESS.ADDRESS_ID
     */
    public void setAddressId(BigDecimal addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.MEMBER_ID
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.MEMBER_ID
     */
    public BigDecimal getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.MEMBER_ID
     *
     * @param memberId the value for T_SSO_MEMBER_ADDRESS.MEMBER_ID
     */
    public void setMemberId(BigDecimal memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.RECEIVER
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.RECEIVER
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.RECEIVER
     *
     * @param receiver the value for T_SSO_MEMBER_ADDRESS.RECEIVER
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.PROVINCE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.PROVINCE
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.PROVINCE
     *
     * @param province the value for T_SSO_MEMBER_ADDRESS.PROVINCE
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.CITY
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.CITY
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.CITY
     *
     * @param city the value for T_SSO_MEMBER_ADDRESS.CITY
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.AREA
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.AREA
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.AREA
     *
     * @param area the value for T_SSO_MEMBER_ADDRESS.AREA
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_NAME
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.ADDRESS_NAME
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_NAME
     *
     * @param addressName the value for T_SSO_MEMBER_ADDRESS.ADDRESS_NAME
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.ZIP
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.ZIP
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.ZIP
     *
     * @param zip the value for T_SSO_MEMBER_ADDRESS.ZIP
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.MOBILE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.MOBILE
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.MOBILE
     *
     * @param mobile the value for T_SSO_MEMBER_ADDRESS.MOBILE
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.TEL
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.TEL
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.TEL
     *
     * @param tel the value for T_SSO_MEMBER_ADDRESS.TEL
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.IS_DEFAULT
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.IS_DEFAULT
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.IS_DEFAULT
     *
     * @param isDefault the value for T_SSO_MEMBER_ADDRESS.IS_DEFAULT
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.IS_DELETE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.IS_DELETE
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.IS_DELETE
     *
     * @param isDelete the value for T_SSO_MEMBER_ADDRESS.IS_DELETE
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.CREATE_DATE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.CREATE_DATE
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.CREATE_DATE
     *
     * @param createDate the value for T_SSO_MEMBER_ADDRESS.CREATE_DATE
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.MODIFY_DATE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.MODIFY_DATE
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.MODIFY_DATE
     *
     * @param modifyDate the value for T_SSO_MEMBER_ADDRESS.MODIFY_DATE
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.FULL_ADDRESS
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.FULL_ADDRESS
     */
    public String getFullAddress() {
        return fullAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.FULL_ADDRESS
     *
     * @param fullAddress the value for T_SSO_MEMBER_ADDRESS.FULL_ADDRESS
     */
    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress == null ? null : fullAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_TYPE
     *
     * @return the value of T_SSO_MEMBER_ADDRESS.ADDRESS_TYPE
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SSO_MEMBER_ADDRESS.ADDRESS_TYPE
     *
     * @param addressType the value for T_SSO_MEMBER_ADDRESS.ADDRESS_TYPE
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType == null ? null : addressType.trim();
    }

    public String getAddressContent() {
        return province + city + area + addressName;
    }
}